apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  labels:
    app: yolo
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
        env: dev
    spec:
      containers:
        - name: yolo
          image: sleemaneketeh/yolo-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_S3_BUCKET
              value: sleeman-polyai-images
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
