apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yolo
  labels:
    app: yolo
    release: monitoring
spec:
  selector:
    matchLabels:
      app: yolo
  namespaceSelector:
    matchNames:
      - dev
      - prod
  endpoints:
    - targetPort: 8080
      path: /metrics
      interval: 30s
