apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  labels:
    app: yolo
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
        env: prod
    spec:
      containers:
        - name: yolo
          image: docker.io/sleemaneketeh/yolo-service:9d21fe64525d7f8e86acdfb8303d71cce86f0b08
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_S3_BUCKET
              value: sleeman-polyai-images
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
