prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi

grafana:
  persistence:
    enabled: true
    type: pvc
    storageClassName: ebs-sc
    accessModes:
      - ReadWriteOnce
    size: 1Gi

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers: ['severity = critical']
        target_matchers: ['severity =~ warning|info']
        equal: ['namespace', 'alertname']
      - source_matchers: ['severity = warning']
        target_matchers: ['severity = info']
        equal: ['namespace', 'alertname']
      - source_matchers: ['alertname = InfoInhibitor']
        target_matchers: ['severity = info']
        equal: ['namespace']
      - target_matchers: ['alertname = InfoInhibitor']
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'sns'
      routes:
        - receiver: 'null'
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: 'null'
      - name: 'sns'
        sns_configs:
          - topic_arn: arn:aws:sns:us-east-1:228281126655:sleeman-polyai-k8s-alerts-topic
            sigv4:
              region: us-east-1
            subject: 'PolyAI Cluster Alert'
    templates:
      - '/etc/alertmanager/config/*.tmpl'
