apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent
  labels:
    app: agent
    release: monitoring
spec:
  selector:
    matchLabels:
      app: agent
  namespaceSelector:
    matchNames:
      - dev
      - prod
  endpoints:
    - targetPort: 8000
      path: /metrics
      interval: 30s
